name: astrobsm-app
services:
  - name: backend
    environment_slug: python
    source_dir: backend
    run_command: chmod +x startup.sh && bash startup.sh
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd ../frontend/react-app
      npm install
      NODE_ENV=production npm run build
      mkdir -p ../../backend/app/static
      cp -r build/* ../../backend/app/static/
      ls -la ../../backend/app/static/
    http_port: 8080
    routes:
      - path: /
    # Note: Set these environment variables in the DigitalOcean App Platform dashboard
    # under Settings > App-Level Environment Variables:
    # - DATABASE_URL: Your PostgreSQL connection string
    # - SECRET_KEY: Your application secret key
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 8080
