name: astrobsm-app
services:
  - name: backend
    environment_slug: python
    source_dir: backend
    run_command: bash start.sh
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd ../frontend/react-app && npm install && NODE_ENV=production npm run build && cp -r build/* ../../backend/app/static/
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: SECRET_KEY
        value: <your_secret_key>
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
