name: astrobsm-app
services:
  - name: backend
    environment_slug: python
    source_dir: backend
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    build_command: |
      pip install -r requirements.txt
      cd ../frontend/react-app
      npm install
      npm run build
      cp -r build/* ../../backend/app/static/
      cd ../../backend/app && alembic upgrade head
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: "<your_database_url>"
      # Add other environment variables as needed
