name: astrobsm-app
services:
  - name: backend
    environment_slug: python
    source_dir: backend
    run_command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --log-level info
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd ../frontend/react-app
      npm install
      NODE_ENV=production npm run build
      mkdir -p ../../backend/app/static
      cp -r build/* ../../backend/app/static/
      ls -la ../../backend/app/static/
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: SECRET_KEY
        value: <your_secret_key>
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

jobs:
  - name: migrate
    environment_slug: python
    source_dir: backend
    run_command: python -m alembic upgrade head
    envs:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: SECRET_KEY
        value: <your_secret_key>
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
